---
# Default variables for pihole
pihole:
  ip: "{{ pihole_ip }}"
  environment:
    WEBPASSWORD: "{{ web_password }}"
    BLOCKING_ENABLED: true
    CACHE_SIZE: 9999
    DNSMASQ_LISTENING: single
    DNS_FQDN_REQUIRED: true
    PIHOLE_DOMAIN: "{{ domain }}"
    QUERY_LOGGING: true
    DNS1: 8.8.8.8
    DNS2: 8.8.4.4
    DNSSEC: false
    DNS_BOGUS_PRIV: true
    CONDITIONAL_FORWARDING: false
  dirs:
    etc: "{{ container.volumes }}/pihole/etc"
    dnsmasq: "{{ container.volumes }}/pihole/etc/dnsmasq.d"
    log: "{{ container.volumes }}/pihole/log"
  dns:
    - "{{ dns }}"
