---
# Default variables for pihole
pihole:
  ip: 192.168.2.254
  environment:
    ADMIN_EMAIL: stevedwray@gmail.com
    WEBPASSWORD: Jahqu3maeGhe6
    BLOCKING_ENABLED: true
    CACHE_SIZE: 9999
    DNSMASQ_LISTENING: single
    DNS_FQDN_REQUIRED: true
    PIHOLE_DOMAIN: lan.local
    QUERY_LOGGING: true
    DNS1: 8.8.8.8
    DNS2: 8.8.4.4
    DNSSEC: false
    DNS_BOGUS_PRIV: true
    CONDITIONAL_FORWARDING: false
    ServerIP: 192.168.1.14
  dirs:
    etc: /srv/usb/pihole/etc
    dnsmasq: /srv/usb/pihole/etc/dnsmasq.d
  dns:
    - 192.168.1.1
