---
- name: Include vars (Deluge)
  include_vars:
    file: deluge.yml
    
- name: Create directories (Deluge)
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ deluge.volumes.config }}"

