---
- name: Include encrypted secret file (LanStack)
  include_vars: secret.yml

- name: Include pihole tasks (LanStack)
  include_tasks: pihole.yml
  tags: pihole
  
- name: Include registry tasks (LanStack)
  include_tasks: registry.yml
  tags: registry
  
- name: Include smb tasks (LanStack)
  include_tasks: smb.yml
  tags: smb
  
- name: Include deluge tasks (LanStack)
  include_tasks: deluge.yml
  tags: deluge
  
- name: Deploy containers using Docker Compose (LanStack)
  tags:
    - compose
    - deluge
    - pihole
    - smb
    - registry
  docker_compose:
    project_name: lanstack
    state: present
    definition:
      version: '3'
      networks:
        ipvlan_net:
          external:
            name: ipvlan_net
      services:
        # I think we are still trying to get the registry working properly.
        # SSL and auth are being a pain.
        registry:
          restart: always
          image: registry:latest
          volumes:
            - "{{ registry.volumes.data }}:/var/lib/registry"
            - "{{ registry.volumes.certs }}:/certs"
            - "{{ registry.volumes.auth }}:/auth"
          environment:
            REGISTRY_AUTH: none
            # REGISTRY_HTTP_ADDR: 0.0.0.0:443
            # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
            # REGISTRY_HTTP_TLS_KEY: /certs/registry.key
            # REGISTRY_AUTH: htpasswd
            # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          networks:
            ipvlan_net:
              ipv4_address: "{{ registry.ip }}"

        # Deluge is working fine.
        deluge:
          restart: always
          image: "{{ deluge.image }}"
          container_name: deluge
          environment:
            - PUID=1000
            - PGID=1000
            # TZ should be a variable:
            - TZ=Pacific/Auckland
            - DELUGE_LOGLEVEL=error
          volumes:
            - "{{ deluge.volumes.config }}:/config"
            - "{{ deluge.volumes.downloads }}:/downloads"
          networks:
            ipvlan_net:
              ipv4_address: "{{ deluge.ip }}"
                  
        pihole:
          restart: always
          image: pihole/pihole:latest
          volumes:
            - "{{ container.volumes }}/pihole/etc-pihole/:/etc/pihole/"
            - "{{ container.volumes }}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
          environment:
            ADMIN_EMAIL: "{{ admin.email }}"
            WEBPASSWORD: "{{ web_password }}"
            BLOCKING_ENABLED: "true"
            CACHE_SIZE: 9999
            DNSMASQ_LISTENING: single
            DNS_FQDN_REQUIRED: "true"
            PIHOLE_DOMAIN: lan.local
            QUERY_LOGGING: "true"
            # These are the upstream DNS servers to use.
            # I'd like to set this up using Cloudflare's DNS over HTTPS though
            # Should be variables, probably all of these:
            DNS1: 192.168.1.1
            DNSSEC: "false"
            DNS_BOGUS_PRIV: "true"
            CONDITIONAL_FORWARDING: "false"
            ServerIP: "{{ pihole.ip }}"
          dns:
            - 192.168.1.1
          networks:
            ipvlan_net:
              ipv4_address: "{{ pihole.ip }}"
