---
- name: Include vars (Pihole)
  include_vars:
    file: pihole.yml

- name: Ensure directories exist (Pihole)
  file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ pihole.dirs | dict2items }}"
