---
- name: Setup Raspberry Pi for Docker
  hosts: pi4a
  remote_user: ansible
  gather_facts: yes
  become: true

  roles:
    - role: docker
      tags: docker_setup
    - role: portainer
      tags: portainer_setup
    - role: lanstack
      tags: lanstack_setup
    - role: jupyterlab
      tags: jupyterlab_setup
      
  vars_files:
    - vars/main.yml

