---
- name: Setup Raspberry Pi for Docker
  hosts: pi4a
  remote_user: ansible
  gather_facts: yes
  become: true

  roles:
    - role: docker
    - role: portainer
      tags: portainer_setup
    - role: cowrie
      tags: cowrie_setup
    - role: snare
      tags: snare_setup

  vars_files:
    - vars/main.yml

