---
- name: Setup Raspberry Pi for Docker
  hosts:
    - kali-pi
    - argon01
    - argon02
  remote_user: ansible
  gather_facts: yes
  become: true

       
  roles:
    - role: base_setup
      tags: base_setup
    - role: docker
      tags: docker
    - role: portainer
      tags: portainer
    - role: lanstack
      tags: lanstack
    - role: jupyterlab
      tags: jupyterlab
    - role: neo4j
      tags: neo4j
  vars_files:
    - vars/main.yml

  
 
