---
- name: Setup Raspberry Pi for Docker
  hosts: pi
  remote_user: ansible
  gather_facts: yes
  become: true

  roles:
    - role: docker
      tags: docker_role
    - role: portainer
      tags: portainer_role
    - role: cowrie
      tags: cowrie_setup

  vars_files:
    - vars/main.yml

  handlers:
    - include: handlers/main.yml
