---
- name: Create Snare volume directory
  file:
    path: "{{ snare_volume_path }}"
    state: directory

- name: Clone Snare Git repository
  git:
    repo: "{{ snare_repo }}"
    dest: "{{ snare_local_src }}"
    version: "main"

- name: Copy index.html to Snare volume directory
  copy:
    src: "{{ playbook_dir }}/roles/snare/files/index.html"
    dest: "{{ snare_volume_path }}/index.html"
    
- name: Build Docker image
  community.general.docker_image:
    name: snare
    tag: latest
    source: build
    build:
      path: "{{ snare_local_src }}"
      args:
        PAGE_URL: "{{ page_url }}"
        #TANNER: "{{ tanner }}"
            
- name: Run Docker container
  community.general.docker_container:
    name: "{{ container_name }}"
    image: "snare:latest"
    state: started
    published_ports:
      - "80:80"
          
