---
usb_device: /dev/sda
usb_partition: /dev/sda1
usb_mount_point: /srv/usb
docker_config_path: /etc/docker/daemon.json
custom_network_file: /tmp/network.yml
sysctl_config_file: /etc/sysctl.conf
docker_data_dir: /srv/usb/docker-data
network_name: docker_network
network_driver: ipvlan
ipvlan_name: ipvlan_net
ipvlan_parent: eth0
ipvlan_network: 192.168.2.0/24
ipvlan_gateway: 192.168.2.1

