---
- name: Include encrypted secret file
  include_vars: secret.yml

- name: Ensure Neo4j directories exist
  ansible.builtin.file:
    path: "{{ neo4j_volume_path }}/{{ item }}"
    state: directory
  loop:
    - data
    - logs
    - conf

- name: Deploy Neo4j container
  community.docker.docker_compose:
    project_name: neo4j
    state: present
    definition:
      version: '3'
      services:
        neo4j:
          image: "{{ neo4j_image }}"
          environment:
            - "NEO4J_AUTH=neo4j/{{ neo4j_password }}"
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
          volumes:
            - "{{ neo4j_volume_path }}/data:/data"
            - "{{ neo4j_volume_path }}/logs:/logs"
            - "{{ neo4j_volume_path }}/conf:/conf"
          networks:
            ipvlan_net:
              ipv4_address: "{{ neo4j_ip }}"
      networks:
        ipvlan_net:
          external:
            name: ipvlan_net

            
