---
- name: Restart Docker Service
  systemd:
    name: docker
    state: restarted

- name: Apply sysctl changes
  command: sysctl -p "{{ sysctl_config_file }}"
  
- name: Restart timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted

- name: Apply network configuration changes
  command: netplan apply
      
