FROM jupyter/base-notebook

ARG JUPYTER_PASSWORD

# Set the Jupyter password
RUN echo "c.LabApp.token='' = '${JUPYTER_PASSWORD}'" >> /home/jovyan/.jupyter/jupyter_notebook_config.py

# Install additional packages if needed
CMD ["jupyter", "notebook", "--ip", "0.0.0.0", "--port", "8888", "--no-browser"]
