---
custom_network_file: /tmp/network.yml
docker:
  config_path: /etc/docker/daemon.json
  data: "{{ container.data }}"
ipvlan:
  # ipvlan settings mostly come from the hosts_vars
  gateway: "{{ ip_vlan_gateway  }}"
  name: ipvlan_net
  network: "{{ ip_vlan_network }}"
  parent: "{{ network_primary_dev }}"
network_driver: ipvlan
network_name: docker_network
sysctl:
  config_file: /etc/sysctl.conf

