---
custom_network_file: /tmp/network.yml
docker:
  config_path: /etc/docker/daemon.json
  data_dir: /srv/usb/docker-data
ipvlan:
  gateway: 192.168.2.1
  name: ipvlan_net
  network: 192.168.2.0/24
  parent: eth0
network_driver: ipvlan
network_name: docker_network
sysctl:
  config_file: /etc/sysctl.conf

