---
- name: Install dependencies on argon01
  delegate_to: "{{ honeypot.build.tanner.host }}"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-dev
    - pip
    
- name: Install Docker library
  delegate_to: "{{ honeypot.build.tanner.host }}"
  pip:
    name: docker
    executable: pip
    state: present
    
- name: Install docker-compose library
  delegate_to: "{{ honeypot.build.tanner.host }}"
  pip:
    name: docker-compose
    executable: pip
    state: present


- name: Create build directory on argon01
  delegate_to: "{{ honeypot.build.tanner.host }}"
  file:
    path: "{{ honeypot.build.tanner.build_dir }}"
    state: directory
    mode: '0755'

# - name: Clone Tanner repository on argon01
#   delegate_to: "{{ honeypot.build.tanner.host }}"
#   git:
#     repo: "{{ honeypot.build.tanner.repo_url }}"
#     dest: "{{ honeypot.build.tanner.build_dir }}"
#     version: "{{ honeypot.build.tanner.repo_version }}"
#     single_branch: yes
#     version: master
#     clone: yes
#     update: no

- name: Run docker-compose to build the container image
  delegate_to: "{{ honeypot.build.tanner.host }}"
  docker_compose:
    project_src: "{{ honeypot.build.tanner.build_dir }}/docker"
    project_name: tanner

- name: Add tag latest to image
  delegate_to: "{{ honeypot.build.tanner.host }}"
  community.docker.docker_image:
    name: tanner_tanner:latest
    repository: "{{ honeypot.tanner.image_name }}"
    force_tag: true
    source: local
    
- name: Push Tanner Docker image to registry on argon01
  delegate_to: "{{ honeypot.build.tanner.host }}"
  docker_image:
    name: tanner_tanner:latest
    repository: 192.168.1.14:5000/tanner
    tag: latest
    push: yes
    source: local

- name: Ensure required directories exist on pi4a
  delegate_to: "{{ honeypot.tanner.host }}"
  file:
    path: "{{ honeypot.tanner.data_dir }}"
    state: directory
    mode: '0755'

- name: Deploy and start Tanner Docker container on pi4a
  delegate_to: "{{ honeypot.tanner.host }}"
  docker_compose:
    project_name: honeypot
    state: present
    definition:
      version: '3'
      networks:
        ipvlan_net:
          external: true
      services:
        tanner:
          image: 192.168.1.14:5000/tanner:latest
          volumes:
            - "{{ honeypot.tanner.data_dir }}:/data"
          networks:
            ipvlan_net:
              ipv4_address: "{{ honeypot.tanner.tanner_ip }}"
          restart: unless-stopped
