---
- name: Restart Docker Service
  systemd:
    name: docker
    state: restarted
    
- name: Apply sysctl changes
  command: sysctl -p "{{ sysctl_config_file }}"

- name: Restart systemd-timesyncd Service
  systemd:
    name: systemd-timesyncd
    state: restarted
