---
# Tasks for Cowrie Docker role

- name: Create directories on target machine
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ cowrie_logs_path }}/cowrie"
    - "{{ cowrie_config_path }}"
    
- name: Copy Cowrie configuration file to target machine
  template:
    src: cowrie.cfg.j2
    dest: "{{ cowrie_config_path }}/cowrie.cfg"
    owner: root
    group: root
    mode: "0644"

- name: Deploy and start Cowrie Docker container
  docker_compose:
    project_name: cowrie
    state: present
    definition:
      version: '3'
      networks:
        ipvlan_net:
          external: true
      services:
        cowrie:
          networks:
            ipvlan_net:
              ipv4_address: "{{ cowrie_ip }}"
          image: "{{ cowrie_docker_image }}"
          volumes:
            - "{{ cowrie_logs_path }}/cowrie:/cowrie/log"
          environment:
            SSH_LISTEN_PORT: 22
            TELNET_LISTEN_PORT: 23

          restart: always

