---
- name: Create temporary directory for Docker Compose files
  tempfile:
    state: directory
  register: compose_temp_dir

- name: Copy Dockerfile to temporary directory
  template:
    src: Dockerfile.j2
    dest: "{{ compose_temp_dir.path }}/Dockerfile"

- name: Create Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ compose_temp_dir.path }}/docker-compose.yml"


- name: Build and start Jupyter container using Docker Compose
  docker_compose:
    project_src: "{{ compose_temp_dir.path }}"
    project_name: jupyter
    build: yes
    state: present
