---
- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Copy Dockerfile to temporary directory
  template:
    src: Dockerfile.j2
    dest: "/tmp/Dockerfile"

- name: Copy docker-compose.yml to temporary directory
  template:
    src: docker-compose.yml.j2
    dest: "/tmp/docker-compose.yml"

- name: Build and run Jupyter container using Docker Compose
  docker_compose:
    project_src: "/tmp"
    files: docker-compose.yml
    state: present
    recreate: always
  environment:
    JUPYTER_PASSWORD: "{{ jupyter_password }}"

