---
- name: Create Portainer data directory
  file:
    path: "{{ portainer_data_dir }}"
    state: directory

- name: Create Portainer networks
  docker_network:
    name: "{{ item.name }}"
    driver: bridge
    ipam_options:
      subnet: "{{ item.subnet }}"
    state: present
  loop: "{{ portainer_networks }}"

- name: Pull Portainer and agent images
  docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - portainer/portainer-ce:latest
    - portainer/agent:latest

- name: Run Portainer container
  docker_container:
    name: portainer-ce
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: unless-stopped
    ports: "{{ portainer_ports }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ portainer_data_dir }}:/data"
    networks:
      - name: Portainer_Net

- name: Run Portainer agent container
  docker_container:
    name: portainer-agent
    image: portainer/agent:latest
    state: started
    restart_policy: unless-stopped
    ports: "{{ portainer_agent_ports }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    networks:
      - name: Portainer_Net
      - name: Portainer_Net_Internal
