---
- name: Include encrypted secret file
  include_vars: secret.yml
  
- name: Create Portainer data directory
  file:
    path: "{{ portainer_data_dir }}"
    state: directory

- name: Pull Portainer and agent images
  docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - portainer/portainer-ce:latest
    - portainer/agent:latest
    

- name: Deploy Portainer using Docker Compose
  docker_compose:
    project_name: portainer
    definition:
      version: '3'
      services:
        portainer-ce:
          restart: always
          image: portainer/portainer-ce
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          networks:
            - portainer-net
            - ipvlan_net
          ports:
            - '{{ portainer_ipvlan }}:9000:9000'
          environment:
            - AGENT_SECRET="{{ agent_secret }}"
          networks:
            ipvlan_net:
              ipv4_address: "{{ portainer_ipvlan }}"
        portainer-agent:
          restart: always
          image: portainer/agent
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
          networks:
            - portainer-net
          environment:
            - AGENT_SECRET="{{ agent_secret }}"
      networks:
        portainer-net:
        ipvlan_net:
          external:
            name: ipvlan_net
