---
portainer:
  data_dir: "{{ container.volumes }}/portainer"
  networks:
    - name: Portainer_Net
      subnet: 192.16.100.0/24
    - name: Portainer_Net_Internal
      subnet: 192.16.101.0/24
  ports:
    - "8000:8000"
    - "9000:9000"
  agent_ports:
    - "9001:9001"
  ip: 192.168.2.15
