---
- name: Modify timesyncd.conf
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    line: "NTP=pool.ntp.org"
    state: present
    backup: yes
    insertafter: EOF
    regexp: "^NTP=.*"
  notify: Restart timesyncd
 
- name: Install Docker and required packages
  apt:
    name:
      - docker.io
      - containerd
      - python3-pip
      - linux-modules-extra-raspi
      - bridge-utils
    state: present
    update_cache: yes
    
- name: Install Python Packages
  pip:
    name:
      - docker
      - docker-compose
      - packaging
    state: present
    
- name: Partition USB drive
  parted:
    device: "{{ usb_device }}"
    number: 1
    state: present
    align: optimal
    label: gpt
    part_end: 100%
    
- name: Create filesystem on the USB partition
  filesystem:
    fstype: ext4
    dev: "{{ usb_partition }}"

- name: Create mount point
  file:
    path: "{{ usb_mount_point }}"
    state: directory

- name: Mount USB drive
  mount:
    path: "{{ usb_mount_point }}"
    src: "{{ usb_partition }}"
    fstype: ext4
    state: mounted

- name: Create Docker directory structure on USB drive
  file:
    path: "{{ docker_data_dir }}"
    state: directory

- name: Copy Docker configuration files to USB drive
  template:
    src: daemon.json.j2
    dest: "{{ docker_config_path }}"

- name: Add macvlan module to /etc/modules
  become: true
  lineinfile:
    path: /etc/modules
    line: "macvlan"
    create: yes
    
- name: Render network configuration file from template
  template:
    src: netplan.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: "0644"
  notify: Apply network configuration changes
 
- name: Enable and start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ansible user to Docker group
  user:
    name: ansible
    groups: docker
    append: yes

- name: Configure sysctl
  template:
    src: sysctl.conf.j2
    dest: "{{ sysctl_config_file }}"
  notify: Apply sysctl changes

