---
- name: Modify timesyncd.conf (Docker)
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    line: "NTP=pool.ntp.org"
    state: present
    backup: yes
    insertafter: EOF
    regexp: "^NTP=.*"
  notify: Restart timesyncd

# There might need to be a delay after this for time to sync?
  
- name: Install Docker and required packages (Docker)
  apt:
    name:
      - docker.io
      - containerd
      - python3-pip
      - linux-modules-extra-raspi
      - bridge-utils
    state: present
    update_cache: yes
    
- name: Install Python Packages (Docker)
  pip:
    name:
      - docker
      - docker-compose
      - packaging
    state: present
    
- name: Partition USB drive (Docker)
  parted:
    device: "{{ usb_device }}"
    number: 1
    state: present
    align: optimal
    label: gpt
    part_end: 100%
    
- name: Create filesystem on the USB partition (Docker)
  filesystem:
    fstype: ext4
    dev: "{{ usb_partition }}"

- name: Create mount point (Docker)
  file:
    path: "{{ usb_mount_point }}"
    state: directory

- name: Mount USB drive (Docker)
  mount:
    path: "{{ usb_mount_point }}"
    src: "{{ usb_partition }}"
    fstype: ext4
    state: mounted

- name: Create Docker directory structure on USB drive (Docker)
  file:
    path: "{{ docker_data_dir }}"
    state: directory

- name: Copy Docker configuration files (Docker)
  template:
    src: daemon.json.j2
    dest: "{{ docker_config_path }}"
  tags:
    - daemon.json

- name: Add ipvlan module to /etc/modules (Docker)
  become: true
  lineinfile:
    path: /etc/modules
    line: "ipvlan"
    create: yes

- name: Create IPvlan network (Docker)
  docker_network:
    name: "{{ ipvlan_name }}"

    driver: ipvlan
    driver_options:
      ipvlan_mode: l3
      parent: "{{ ipvlan_parent }}"
    ipam_config:
      - subnet: "{{ ipvlan_network }}"
        gateway: "{{ ipvlan_gateway }}"
    
- name: Enable and start Docker service (Docker)
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ansible user to Docker group (Docker)
  user:
    name: ansible
    groups: docker
    append: yes

- name: Configure sysctl (Docker)
  template:
    src: sysctl.conf.j2
    dest: "{{ sysctl_config_file }}"
  notify: Apply sysctl changes

