---
- name: Include vars (Docker)
  include_vars:
    file: main.yml

- name: Repo and key for Debian
  block:    
    - name: Download Docker GPG key
      get_url:
        url: "https://download.docker.com/linux/debian/gpg"
        dest: "/etc/apt/keyrings/docker.gpg"
        mode: '0644'
        validate_certs: yes
  
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
  when: ansible_distribution in ['Debian']

  
- name: Install Docker and required packages (Docker)
  apt:
    name:
      - python3-pip
      - bridge-utils
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

    
- name: Install Docker and required packages (Docker)
  apt:
    name:
      - docker.io
      - containerd
    state: present
    update_cache: yes
  when: ansible_distribution in ['Ubuntu', 'Kali']

- name: Install Docker and required packages (Docker)
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-ce-rootless-extras
      - docker-buildx-plugin
    state: present
    update_cache: yes
  when: ansible_distribution in ['Debian']

  
- name: Install Ubuntu-specific packages (Docker)
  apt:
    name: linux-modules-extra-raspi
    state: present
  when: ansible_distribution == 'Ubuntu'
    
- name: Install Python Packages (Docker)
  pip:
    name:
      - docker
      - docker-compose
      - packaging
    state: present

- name: Create Docker directory structure (Docker)
  file:
    path: "{{ container.data }}"
    state: directory

- name: Copy Docker configuration files (Docker)
  template:
    src: daemon.json.j2
    dest: "{{ docker.config_path }}"
  tags:
    - daemon.json

- name: Add ipvlan module to /etc/modules (Docker)
  become: true
  lineinfile:
    path: /etc/modules
    line: "ipvlan"
    create: yes

- name: Create IPvlan network (Docker)
  docker_network:
    name: "{{ ipvlan.name }}"
    driver: ipvlan
    driver_options:
      ipvlan_mode: l3
      parent: "{{ ipvlan.parent }}"
    ipam_config:
      - subnet: "{{ ipvlan.network }}"
        gateway: "{{ ipvlan.gateway }}"
    
- name: Enable and start Docker service (Docker)
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ansible user to Docker group (Docker)
  user:
    name: ansible
    groups: docker
    append: yes

- name: Configure sysctl (Docker)
  template:
    src: sysctl.conf.j2
    dest: "{{ sysctl.config_file }}"
  notify: Apply sysctl changes

