---
- name: Include vars (Docker)
  include_vars:
    file: main.yml
  
- name: Install Docker and required packages (Docker)
  apt:
    name:
      - docker.io
      - containerd
      - python3-pip
      - bridge-utils
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Install Ubuntu-specific packages (Docker)
  apt:
    name: linux-modules-extra-raspi
    state: present
  when: ansible_distribution == 'Ubuntu'
    
- name: Install Python Packages (Docker)
  pip:
    name:
      - docker
      - docker-compose
      - packaging
    state: present
    

- name: Create Docker directory structure (Docker)
  file:
    path: "{{ container.data }}"
    state: directory

- name: Copy Docker configuration files (Docker)
  template:
    src: daemon.json.j2
    dest: "{{ docker.config_path }}"
  tags:
    - daemon.json

- name: Add ipvlan module to /etc/modules (Docker)
  become: true
  lineinfile:
    path: /etc/modules
    line: "ipvlan"
    create: yes

- name: Create IPvlan network (Docker)
  docker_network:
    name: "{{ ipvlan.name }}"
    driver: ipvlan
    driver_options:
      ipvlan_mode: l3
      parent: "{{ ipvlan.parent }}"
    ipam_config:
      - subnet: "{{ ipvlan.network }}"
        gateway: "{{ ipvlan.gateway }}"
    
- name: Enable and start Docker service (Docker)
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ansible user to Docker group (Docker)
  user:
    name: ansible
    groups: docker
    append: yes

- name: Configure sysctl (Docker)
  template:
    src: sysctl.conf.j2
    dest: "{{ sysctl.config_file }}"
  notify: Apply sysctl changes

