---
jupyter:
  image:
    name: my-jupyter-image
  container:
    name: my-jupyter-container
  dockerfile:
    path: /tmp/Dockerfile
  password: "argon2:$argon2id$v=19$m=10240,t=10,p=8$2CSUm3TsIS761WGkmuK/LA$0Iy5WFyiAgmv0y1ERufhIfoNHRExRe23q1uf83mxjSI"
  volume:
    path: "{{ container.volumes }}/jupyter"
  ssl:
    certificate:
      path: cert
    key:
      path: key
  ip: "{{ jupyter_ip }}"
  port: 443
