---
- name: Include encrypted secret file
  include_vars: secret.yml
  
- name: Create Jupyter volume directory
  file:
    path: "{{ jupyter.volume_path }}"
    state: directory
    mode: '0755'
- name: Create Jupyter cert directory
  file:
    path: "{{ jupyter.volume_path }}/{{ jupyter.ssl_certificate_path }}"
    state: directory
    mode: '0750'
- name: Create Jupyter key directory
  file:
    path: "{{ jupyter.volume_path }}/{{ jupyter.ssl_key_path }}"
    state: directory
    mode: '0750'

- name: Generate self-signed TLS certificate and key
  openssl_privatekey:
    path: "{{ jupyter.volume_path }}/{{ jupyter.ssl_key_path }}/jupyter.key"
    size: 2048
    type: RSA
    mode: '0600'

- name: Generate self-signed TLS certificate
  openssl_certificate:
    path: "{{ jupyter.volume_path }}/{{ jupyter.ssl_certificate_path }}/jupyter.crt"
    privatekey_path: "{{ jupyter.volume_path }}/{{ jupyter.ssl_key_path }}/jupyter.key"
    provider: selfsigned
    force: yes

- name: Deploy JupyterLab container
  docker_compose:
    project_name: jupyterlab
    state: present
    definition:
      version: '3'
      services:
        jupyter:
          image: bitnami/jupyter-base-notebook:latest
          ports:
            - "{{ jupyter.ip}}:443:8888"
          environment:
            - JUPYTER_ENABLE_LAB=yes
            - JUPYTER_PASSWORD={{ vault_jupyter_password }}
          volumes:
            - "{{ jupyter.volume_path }}:/home/jovyan/work"
            - "{{ jupyter.volume_path }}/{{ jupyter.ssl_certificate_path }}/jupyter.crt:/etc/jupyter/ssl/jupytercert.crt:ro"
            - "{{ jupyter.volume_path }}/{{ jupyter.ssl_key_path }}/jupyter.key:/etc/jupyter/ssl/jupytercert.key:ro"
          networks:
            ipvlan_net:
              ipv4_address: "{{ jupyter.ip }}"
      networks:
        ipvlan_net:
          external:
            name: ipvlan_net
