---
- name: Include encrypted secret file
  include_vars: secret.yml
  
- name: Create Jupyter volume directory
  file:
    path: "{{ jupyter.volume.path }}"
    state: directory
    mode: '0755'
- name: Create Jupyter cert directory
  file:
    path: "{{ jupyter.volume.path }}/{{ jupyter.ssl.certificate.path }}"
    state: directory
    mode: '0750'
- name: Create Jupyter key directory
  file:
    path: "{{ jupyter.volume.path }}/{{ jupyter.ssl.key.path }}"
    state: directory
    mode: '0750'

- name: Deploy JupyterLab container
  docker_compose:
    project_name: jupyterlab
    state: present
    definition:
      version: '3'
      services:
        jupyter:
          image: jupyter/base-notebook
          environment:
            - GEN_CERT=yes
            - NOTEBOOK_ARGS=--NotebookApp.token="{{ jupyter_token }}"
            - "JUPYTER_PORT={{ jupyter.port }}"
          volumes:
            # I'm going to want to put this somewhere I can actually drop files etc
            - "/srv/media/gazaar/documents/Jupyter:/home/jovyan/work"
            - "{{ jupyter.volume.path }}/{{ jupyter.ssl.certificate.path }}/jupyter.crt:/etc/jupyter/ssl/jupytercert.crt:ro"
            - "{{ jupyter.volume.path }}/{{ jupyter.ssl.key.path }}/jupyter.key:/etc/jupyter/ssl/jupytercert.key:ro"
          networks:
            ipvlan_net:
              ipv4_address: "{{ jupyter.ip }}"
      networks:
        ipvlan_net:
          external:
            name: ipvlan_net
